### ISSUE TITLE
antspyx==0.3.2 not available 

### ISSUE THREAD

**Issue by adrianvallsc** [NOEL-MNI/deepFCD#12]
When trying to install requirements, antspyx version 0.3.2 does not exist anymore.

**Comment by ravnoor** [comment]
Thanks for reporting! It looks there are PyPi size limitations on the `antspyx` account that cause older versions to be deleted/removed.

For now, you can safely edit `app/requirements.txt` to bump the version to `antspyx==0.3.5`, and `app/deepMask/app/requirements.txt` to bump the versions `antspyx==0.3.5` and `antspynet==0.2.0`.

I'll test the changes and push updates in a few days to initiate the docker image rebuild
