### ISSUE TITLE
Output predictions in structural space

### ISSUE THREAD

**Issue by 1-w** [NOEL-MNI/deepFCD#8]
## Description
How can the internal coregistration via deepmask be reversed 

## Actual Behavior
Output is always normalized.

## Possible Fix.
Allow a flag to translate predictions back to input space.

**Comment by ravnoor** [comment]
Feature also requested by `Mia.Mojica at uhn dot ca` on 03/08/2022 via email:
> a) store the transformations warping the original T1w and FLAIR images to MNI space during the registration stage and
> b) invert these transformations to view the probability maps in native space
